import type { Question } from '@/types/question';

export const questionsPart3: Question[] = [
  // === T4A - Station Setup & Operation ===
  {
    id: 'T4A01',
    question: 'Which of the following is true concerning the microphone connectors on amateur transceivers?',
    answers: ['All transceivers use the same microphone connector type', 'Some connectors include push-to-talk and voltages for powering the microphone', 'All transceivers using the same connector type are wired identically', 'Un-keyed connectors exist only on handheld transceivers'],
    correctIndex: 1,
    explanation: 'Some microphone connectors include push-to-talk and voltages for powering the microphone, but not all transceivers use the same connector or wiring.',
    category: 'T4',
    subcategory: 'T4A',
  },
  {
    id: 'T4A02',
    question: 'How might a computer be used as part of an amateur radio station?',
    answers: ['For logging contacts and contact information', 'For sending and receiving CW', 'For generating and decoding digital signals', 'All these choices are correct'],
    correctIndex: 3,
    explanation: 'A computer can be used for logging contacts, sending and receiving CW, and generating and decoding digital signals.',
    category: 'T4',
    subcategory: 'T4A',
  },
  {
    id: 'T4A03',
    question: 'Which is a good reason to use a regulated power supply for communications equipment?',
    answers: ['It prevents voltage fluctuations from reaching sensitive circuits', 'A regulated power supply has FCC approval', 'A fuse or circuit breaker regulates the power', 'Power consumption is independent of load'],
    correctIndex: 0,
    explanation: 'A regulated power supply prevents voltage fluctuations from reaching sensitive circuits, providing stable voltage to the equipment.',
    category: 'T4',
    subcategory: 'T4A',
  },
  {
    id: 'T4A04',
    question: 'Where must a filter be installed to reduce harmonic emissions from your station?',
    answers: ['Between the transmitter and the antenna', 'Between the receiver and the transmitter', 'At the station power supply', 'At the microphone'],
    correctIndex: 0,
    explanation: 'A filter should be installed between the transmitter and the antenna to reduce harmonic emissions.',
    category: 'T4',
    subcategory: 'T4A',
  },
  {
    id: 'T4A05',
    question: 'Where should an in-line SWR meter be connected to monitor the standing wave ratio of the station antenna system?',
    answers: ['In series with the feed line, between the transmitter and antenna', 'In series with the station\'s ground', 'In parallel with the push-to-talk line and the antenna', 'In series with the power supply cable, as close as possible to the radio'],
    correctIndex: 0,
    explanation: 'An in-line SWR meter should be connected in series with the feed line, between the transmitter and antenna.',
    category: 'T4',
    subcategory: 'T4A',
  },
  {
    id: 'T4A06',
    question: 'Which of the following would be connected between a transceiver and computer in a packet radio station?',
    answers: ['Transmatch', 'Terminal node controller', 'Antenna', 'On/off switch'],
    correctIndex: 1,
    explanation: 'A Terminal Node Controller (TNC) is connected between a transceiver and computer in a packet radio station.',
    category: 'T4',
    subcategory: 'T4A',
  },
  {
    id: 'T4A07',
    question: 'How is a computer\'s sound card used when conducting digital communications?',
    answers: ['The sound card communicates between the computer CPU and the video display', 'The sound card records the audio frequency for digital modes. Sound cards provide audio to the radio\'s microphone input and convert received audio to digital form', 'All of these choices are correct', 'The sound card provides DC power to the interface'],
    correctIndex: 1,
    explanation: 'A sound card is used to provide audio to the radio\'s microphone input and to convert received audio to digital form for digital mode communications.',
    category: 'T4',
    subcategory: 'T4A',
  },
  {
    id: 'T4A08',
    question: 'Which type of conductor is best to use for RF grounding?',
    answers: ['Round stranded wire', 'Round copper-clad steel wire', 'Twisted-pair cable', 'Flat strap'],
    correctIndex: 3,
    explanation: 'Flat strap is the best type of conductor to use for RF grounding because it has lower inductance than round wire.',
    category: 'T4',
    subcategory: 'T4A',
  },
  {
    id: 'T4A09',
    question: 'Which of the following could you use to cure distorted audio caused by RF current on the shield of a microphone cable?',
    answers: ['Low-pass filter', 'Squelch adjustment', 'RF choke', 'Band-pass filter'],
    correctIndex: 2,
    explanation: 'An RF choke can be used to cure distorted audio caused by RF current on the shield of a microphone cable.',
    category: 'T4',
    subcategory: 'T4A',
  },
  // === T4B - Operating Controls & Settings ===
  {
    id: 'T4B01',
    question: 'What is the effect of increasing the microphone gain on a transmitter?',
    answers: ['The transmitted signal might become distorted', 'The frequency stability might improve', 'The SWR might increase', 'The transmitted power might decrease'],
    correctIndex: 0,
    explanation: 'Increasing the microphone gain too high can cause the transmitted signal to become distorted.',
    category: 'T4',
    subcategory: 'T4B',
  },
  {
    id: 'T4B02',
    question: 'Which of the following can be used to enter the operating frequency on a modern transceiver?',
    answers: ['The keypad or VFO knob', 'The CTCSS or DTMF encoder', 'The Automatic Frequency Control', 'All these choices are correct'],
    correctIndex: 0,
    explanation: 'The keypad or VFO (Variable Frequency Oscillator) knob can be used to enter the operating frequency on a modern transceiver.',
    category: 'T4',
    subcategory: 'T4B',
  },
  {
    id: 'T4B03',
    question: 'What is the purpose of the squelch control on a transceiver?',
    answers: ['To set the highest level of volume desired', 'To set the transmitter power level', 'To mute the receiver audio output when no signal is present', 'To adjust the automatic gain control'],
    correctIndex: 2,
    explanation: 'The squelch control mutes the receiver audio output when no signal is present, eliminating background noise.',
    category: 'T4',
    subcategory: 'T4B',
  },
  {
    id: 'T4B04',
    question: 'What is a way to enable quick access to a favorite frequency on your transceiver?',
    answers: ['Enable the CTCSS tones', 'Store the frequency in a memory channel', 'Disable the CTCCS tones', 'Use the scan mode to select the desired frequency'],
    correctIndex: 1,
    explanation: 'Storing the frequency in a memory channel enables quick access to a favorite frequency.',
    category: 'T4',
    subcategory: 'T4B',
  },
  {
    id: 'T4B05',
    question: 'Which of the following would reduce ignition interference to a receiver?',
    answers: ['Change frequency slightly', 'Decrease the squelch setting', 'Turn on the noise blanker', 'Use the RIT control'],
    correctIndex: 2,
    explanation: 'Turning on the noise blanker can reduce ignition interference to a receiver.',
    category: 'T4',
    subcategory: 'T4B',
  },
  {
    id: 'T4B06',
    question: 'Which of the following controls could be used if the voice pitch of a single-sideband signal seems too high or low?',
    answers: ['The AGC or limiter', 'The bandwidth selection', 'The tone squelch', 'The RIT or Clarifier'],
    correctIndex: 3,
    explanation: 'The RIT (Receiver Incremental Tuning) or Clarifier control can be used if the voice pitch of a single-sideband signal seems too high or low.',
    category: 'T4',
    subcategory: 'T4B',
  },
  {
    id: 'T4B07',
    question: 'What does the term \'RIT\' mean?',
    answers: ['Receiver Input Tone', 'Receiver Incremental Tuning', 'Rectifier Inverter Test', 'Remote Input Transmitter'],
    correctIndex: 1,
    explanation: 'RIT stands for Receiver Incremental Tuning, which allows fine adjustment of the receiver frequency without affecting the transmitter frequency.',
    category: 'T4',
    subcategory: 'T4B',
  },
  {
    id: 'T4B08',
    question: 'What is the advantage of having multiple receive bandwidth choices on a multimode transceiver?',
    answers: ['Permits monitoring several modes at once', 'Permits noise or interference reduction by selecting a bandwidth matching the mode', 'Increases the number of frequencies that can be stored in memory', 'Increases the amount of offset between receive and transmit frequencies'],
    correctIndex: 1,
    explanation: 'Multiple receive bandwidth choices permit noise or interference reduction by selecting a bandwidth matching the mode.',
    category: 'T4',
    subcategory: 'T4B',
  },
  {
    id: 'T4B09',
    question: 'Which of the following is an appropriate receive filter bandwidth to select in order to minimize noise and interference for SSB reception?',
    answers: ['500 Hz', '2700 Hz', '2400 Hz', '15,000 Hz'],
    correctIndex: 2,
    explanation: 'A bandwidth of approximately 2400 Hz is appropriate for SSB reception to minimize noise and interference.',
    category: 'T4',
    subcategory: 'T4B',
  },
  {
    id: 'T4B10',
    question: 'Which of the following is an appropriate receive filter bandwidth to select in order to minimize noise and interference for CW reception?',
    answers: ['500 Hz', '2700 Hz', '2400 Hz', '15,000 Hz'],
    correctIndex: 0,
    explanation: 'A bandwidth of approximately 500 Hz is appropriate for CW reception to minimize noise and interference.',
    category: 'T4',
    subcategory: 'T4B',
  },
  {
    id: 'T4B11',
    question: 'Which of the following describes the common meaning of the term \'repeater offset\'?',
    answers: ['The distance between the repeater\'s transmit and receive antennas', 'The time delay before the repeater transmitter resets', 'The difference between the repeater\'s transmit and receive frequencies', 'Matching the antenna impedance to the feed line impedance'],
    correctIndex: 2,
    explanation: 'Repeater offset refers to the difference between the repeater\'s transmit and receive frequencies.',
    category: 'T4',
    subcategory: 'T4B',
  },
  {
    id: 'T4B12',
    question: 'What is the function of automatic gain control, or AGC?',
    answers: ['To keep received audio relatively constant', 'To protect an antenna from lightning', 'To eliminate RF on the station cabling', 'To regulate the transmitter power output'],
    correctIndex: 0,
    explanation: 'Automatic Gain Control (AGC) keeps received audio relatively constant despite varying signal strengths.',
    category: 'T4',
    subcategory: 'T4B',
  },
  // === T5A - Electrical Units ===
  {
    id: 'T5A01',
    question: 'Electrical current is measured in which of the following units?',
    answers: ['Volts', 'Watts', 'Ohms', 'Amperes'],
    correctIndex: 3,
    explanation: 'Electrical current is measured in amperes (amps). Voltage is measured in volts, power in watts, and resistance in ohms.',
    category: 'T5',
    subcategory: 'T5A',
  },
  {
    id: 'T5A02',
    question: 'Electrical power is measured in which of the following units?',
    answers: ['Volts', 'Watts', 'Ohms', 'Amperes'],
    correctIndex: 1,
    explanation: 'Electrical power is measured in watts. Power is the rate at which electrical energy is used.',
    category: 'T5',
    subcategory: 'T5A',
  },
  {
    id: 'T5A03',
    question: 'What is the name for the flow of electrons in an electric circuit?',
    answers: ['Voltage', 'Resistance', 'Capacitance', 'Current'],
    correctIndex: 3,
    explanation: 'Current is the flow of electrons in an electric circuit.',
    category: 'T5',
    subcategory: 'T5A',
  },
  {
    id: 'T5A04',
    question: 'What is the name for a current that flows only in one direction?',
    answers: ['Alternating current', 'Direct current', 'Normal current', 'Smooth current'],
    correctIndex: 1,
    explanation: 'Direct current (DC) flows only in one direction. Alternating current (AC) periodically reverses direction.',
    category: 'T5',
    subcategory: 'T5A',
  },
  {
    id: 'T5A05',
    question: 'What is the electrical term for the electromotive force (EMF) that causes electron flow?',
    answers: ['Voltage', 'Ampere-hours', 'Capacitance', 'Inductance'],
    correctIndex: 0,
    explanation: 'Voltage is the electrical term for the electromotive force (EMF) that causes electron flow.',
    category: 'T5',
    subcategory: 'T5A',
  },
  {
    id: 'T5A06',
    question: 'How much voltage does a mobile transceiver usually require?',
    answers: ['About 12 volts', 'About 30 volts', 'About 120 volts', 'About 240 volts'],
    correctIndex: 0,
    explanation: 'Mobile transceivers usually require about 12 volts, which is the standard voltage for automotive electrical systems.',
    category: 'T5',
    subcategory: 'T5A',
  },
  // === T5B - Math for Electronics ===
  {
    id: 'T5B01',
    question: 'How many milliamperes is 1.5 amperes?',
    answers: ['15 milliamperes', '150 milliamperes', '1500 milliamperes', '15,000 milliamperes'],
    correctIndex: 2,
    explanation: '1.5 amperes = 1500 milliamperes. There are 1000 milliamperes in 1 ampere.',
    category: 'T5',
    subcategory: 'T5B',
  },
  {
    id: 'T5B02',
    question: 'What is another way to specify a radio signal frequency of 1,500,000 hertz?',
    answers: ['1500 kHz', '1500 MHz', '15 GHz', '150 kHz'],
    correctIndex: 0,
    explanation: '1,500,000 hertz = 1500 kHz (kilohertz). There are 1000 hertz in 1 kilohertz.',
    category: 'T5',
    subcategory: 'T5B',
  },
  {
    id: 'T5B03',
    question: 'How many volts are equal to one kilovolt?',
    answers: ['One one-thousandth of a volt', 'One hundred volts', 'One thousand volts', 'One million volts'],
    correctIndex: 2,
    explanation: 'One kilovolt equals one thousand volts. The prefix \'kilo\' means 1000.',
    category: 'T5',
    subcategory: 'T5B',
  },
  {
    id: 'T5B04',
    question: 'How many volts are equal to one microvolt?',
    answers: ['One one-millionth of a volt', 'One thousand volts', 'One million volts', 'One one-thousandth of a volt'],
    correctIndex: 0,
    explanation: 'One microvolt equals one one-millionth of a volt. The prefix \'micro\' means 10^-6.',
    category: 'T5',
    subcategory: 'T5B',
  },
  {
    id: 'T5B05',
    question: 'Which of the following is equivalent to 500 milliwatts?',
    answers: ['0.02 watts', '0.5 watts', '5 watts', '50 watts'],
    correctIndex: 1,
    explanation: '500 milliwatts = 0.5 watts. There are 1000 milliwatts in 1 watt.',
    category: 'T5',
    subcategory: 'T5B',
  },
  {
    id: 'T5B06',
    question: 'If an ammeter calibrated in amperes is used to measure a 3000-milliampere current, what reading would it show?',
    answers: ['0.003 amperes', '0.3 amperes', '3 amperes', '3,000,000 amperes'],
    correctIndex: 2,
    explanation: '3000 milliamperes = 3 amperes. Divide by 1000 to convert from milliamperes to amperes.',
    category: 'T5',
    subcategory: 'T5B',
  },
  {
    id: 'T5B07',
    question: 'If a frequency readout calibrated in megahertz shows a reading of 3.525 MHz, what would it show if it were calibrated in kilohertz?',
    answers: ['0.003525 kHz', '35.25 kHz', '3525 kHz', '3,525,000 kHz'],
    correctIndex: 2,
    explanation: '3.525 MHz = 3525 kHz. Multiply by 1000 to convert from MHz to kHz.',
    category: 'T5',
    subcategory: 'T5B',
  },
  {
    id: 'T5B08',
    question: 'How many microfarads are 1,000,000 picofarads?',
    answers: ['0.001 microfarads', '1 microfarad', '1000 microfarads', '1,000,000,000 microfarads'],
    correctIndex: 1,
    explanation: '1,000,000 picofarads = 1 microfarad. There are 1,000,000 picofarads in 1 microfarad.',
    category: 'T5',
    subcategory: 'T5B',
  },
  {
    id: 'T5B09',
    question: 'What is the approximate amount of change, measured in decibels (dB), of a power increase from 5 watts to 10 watts?',
    answers: ['2 dB', '3 dB', '5 dB', '10 dB'],
    correctIndex: 1,
    explanation: 'A doubling of power is approximately a 3 dB increase. Going from 5 watts to 10 watts doubles the power.',
    category: 'T5',
    subcategory: 'T5B',
  },
  {
    id: 'T5B10',
    question: 'What is the approximate amount of change, measured in decibels (dB), of a power decrease from 12 watts to 3 watts?',
    answers: ['-1 dB', '-3 dB', '-6 dB', '-9 dB'],
    correctIndex: 2,
    explanation: 'Going from 12 watts to 3 watts is a factor of 4 decrease (12/3 = 4). A factor of 4 change is approximately 6 dB (since each halving is 3 dB, and 4 = 2×2). Since it\'s a decrease, it is -6 dB.',
    category: 'T5',
    subcategory: 'T5B',
  },
  {
    id: 'T5B11',
    question: 'What is the approximate amount of change, measured in decibels (dB), of a power increase from 20 watts to 200 watts?',
    answers: ['10 dB', '12 dB', '18 dB', '28 dB'],
    correctIndex: 0,
    explanation: 'Going from 20 watts to 200 watts is a factor of 10 increase. A factor of 10 change equals 10 dB.',
    category: 'T5',
    subcategory: 'T5B',
  },
  {
    id: 'T5B12',
    question: 'Which of the following frequencies is equal to 28,400 kHz?',
    answers: ['28.400 MHz', '2.800 MHz', '284.00 MHz', '28,400 MHz'],
    correctIndex: 0,
    explanation: '28,400 kHz = 28.400 MHz. Divide by 1000 to convert from kHz to MHz.',
    category: 'T5',
    subcategory: 'T5B',
  },
  // === T5C - Electronic Principles ===
  {
    id: 'T5C01',
    question: 'What is the ability to store energy in an electric field called?',
    answers: ['Inductance', 'Resistance', 'Tolerance', 'Capacitance'],
    correctIndex: 3,
    explanation: 'Capacitance is the ability to store energy in an electric field. A capacitor stores energy in this way.',
    category: 'T5',
    subcategory: 'T5C',
  },
  {
    id: 'T5C02',
    question: 'What is the basic unit of capacitance?',
    answers: ['The farad', 'The ohm', 'The volt', 'The henry'],
    correctIndex: 0,
    explanation: 'The farad is the basic unit of capacitance. The ohm is the unit of resistance, the volt is the unit of voltage, and the henry is the unit of inductance.',
    category: 'T5',
    subcategory: 'T5C',
  },
  {
    id: 'T5C03',
    question: 'What is the ability to store energy in a magnetic field called?',
    answers: ['Admittance', 'Capacitance', 'Resistance', 'Inductance'],
    correctIndex: 3,
    explanation: 'Inductance is the ability to store energy in a magnetic field. An inductor stores energy in this way.',
    category: 'T5',
    subcategory: 'T5C',
  },
  {
    id: 'T5C04',
    question: 'What is the basic unit of inductance?',
    answers: ['The coulomb', 'The farad', 'The henry', 'The ohm'],
    correctIndex: 2,
    explanation: 'The henry is the basic unit of inductance. The farad is the unit of capacitance, the coulomb is the unit of charge, and the ohm is the unit of resistance.',
    category: 'T5',
    subcategory: 'T5C',
  },
  {
    id: 'T5C05',
    question: 'What is the unit of frequency?',
    answers: ['Hertz', 'Henry', 'Farad', 'Tesla'],
    correctIndex: 0,
    explanation: 'The hertz is the unit of frequency. One hertz equals one cycle per second.',
    category: 'T5',
    subcategory: 'T5C',
  },
  {
    id: 'T5C06',
    question: 'What does the abbreviation \'RF\' refer to?',
    answers: ['Radio frequency signals of all types', 'The resonant frequency of a tuned circuit', 'The real frequency transmitted as opposed to the apparent frequency', 'Reflective force in antenna transmission lines'],
    correctIndex: 0,
    explanation: '\'RF\' stands for radio frequency, referring to radio frequency signals of all types.',
    category: 'T5',
    subcategory: 'T5C',
  },
  {
    id: 'T5C07',
    question: 'What is a usual name for electromagnetic waves that travel through space?',
    answers: ['Gravity waves', 'Sound waves', 'Radio waves', 'Pressure waves'],
    correctIndex: 2,
    explanation: 'Radio waves are electromagnetic waves that travel through space.',
    category: 'T5',
    subcategory: 'T5C',
  },
  {
    id: 'T5C08',
    question: 'What is the formula used to calculate electrical power in a DC circuit?',
    answers: ['Power (P) equals voltage (E) multiplied by current (I)', 'Power (P) equals voltage (E) divided by current (I)', 'Power (P) equals voltage (E) minus current (I)', 'Power (P) equals voltage (E) plus current (I)'],
    correctIndex: 0,
    explanation: 'Power (P) = Voltage (E) × Current (I), or P = EI.',
    category: 'T5',
    subcategory: 'T5C',
  },
  {
    id: 'T5C09',
    question: 'How much power is being used in a circuit when the applied voltage is 13.8 volts DC and the current is 10 amperes?',
    answers: ['138 watts', '0.7 watts', '23.8 watts', '3.8 watts'],
    correctIndex: 0,
    explanation: 'Power = Voltage × Current = 13.8 V × 10 A = 138 watts.',
    category: 'T5',
    subcategory: 'T5C',
  },
  {
    id: 'T5C10',
    question: 'How much power is being used in a circuit when the applied voltage is 12 volts DC and the current is 2.5 amperes?',
    answers: ['4.8 watts', '30 watts', '14.5 watts', '0.208 watts'],
    correctIndex: 1,
    explanation: 'Power = Voltage × Current = 12 V × 2.5 A = 30 watts.',
    category: 'T5',
    subcategory: 'T5C',
  },
  {
    id: 'T5C11',
    question: 'What is meant by the term impedance?',
    answers: ['It is a measure of the opposition to AC current flow in a circuit', 'It is the inverse of resistance', 'It is a measure of the Q or Quality Factor of a component', 'It is a measure of the power handling capability of a component'],
    correctIndex: 0,
    explanation: 'Impedance is a measure of the opposition to AC current flow in a circuit. It includes both resistance and reactance.',
    category: 'T5',
    subcategory: 'T5C',
  },
  {
    id: 'T5C12',
    question: 'What are the units of impedance?',
    answers: ['Volts', 'Amperes', 'Coulombs', 'Ohms'],
    correctIndex: 3,
    explanation: 'Impedance is measured in ohms, the same unit as resistance.',
    category: 'T5',
    subcategory: 'T5C',
  },
  // === T5D - Ohm's Law ===
  {
    id: 'T5D01',
    question: 'What formula is used to calculate current in a circuit?',
    answers: ['Current (I) equals voltage (E) multiplied by resistance (R)', 'Current (I) equals voltage (E) divided by resistance (R)', 'Current (I) equals voltage (E) added to resistance (R)', 'Current (I) equals voltage (E) minus resistance (R)'],
    correctIndex: 1,
    explanation: 'Current (I) = Voltage (E) / Resistance (R), or I = E/R (Ohm\'s Law).',
    category: 'T5',
    subcategory: 'T5D',
  },
  {
    id: 'T5D02',
    question: 'What formula is used to calculate voltage in a circuit?',
    answers: ['Voltage (E) equals current (I) multiplied by resistance (R)', 'Voltage (E) equals current (I) divided by resistance (R)', 'Voltage (E) equals current (I) added to resistance (R)', 'Voltage (E) equals current (I) minus resistance (R)'],
    correctIndex: 0,
    explanation: 'Voltage (E) = Current (I) × Resistance (R), or E = IR (Ohm\'s Law).',
    category: 'T5',
    subcategory: 'T5D',
  },
  {
    id: 'T5D03',
    question: 'What formula is used to calculate resistance in a circuit?',
    answers: ['Resistance (R) equals voltage (E) multiplied by current (I)', 'Resistance (R) equals voltage (E) divided by current (I)', 'Resistance (R) equals voltage (E) added to current (I)', 'Resistance (R) equals voltage (E) minus current (I)'],
    correctIndex: 1,
    explanation: 'Resistance (R) = Voltage (E) / Current (I), or R = E/I (Ohm\'s Law).',
    category: 'T5',
    subcategory: 'T5D',
  },
  {
    id: 'T5D04',
    question: 'What is the resistance of a circuit in which a current of 3 amperes flows through a resistor connected to 90 volts?',
    answers: ['3 ohms', '30 ohms', '93 ohms', '270 ohms'],
    correctIndex: 1,
    explanation: 'R = E/I = 90 V / 3 A = 30 ohms.',
    category: 'T5',
    subcategory: 'T5D',
  },
  {
    id: 'T5D05',
    question: 'What is the resistance in a circuit for which the applied voltage is 12 volts and the current flow is 1.5 amperes?',
    answers: ['18 ohms', '0.125 ohms', '8 ohms', '13.5 ohms'],
    correctIndex: 2,
    explanation: 'R = E/I = 12 V / 1.5 A = 8 ohms.',
    category: 'T5',
    subcategory: 'T5D',
  },
  {
    id: 'T5D06',
    question: 'What is the resistance of a circuit that draws 4 amperes from a 12-volt source?',
    answers: ['3 ohms', '16 ohms', '48 ohms', '8 ohms'],
    correctIndex: 0,
    explanation: 'R = E/I = 12 V / 4 A = 3 ohms.',
    category: 'T5',
    subcategory: 'T5D',
  },
  {
    id: 'T5D07',
    question: 'What is the current in a circuit with an applied voltage of 120 volts and a resistance of 80 ohms?',
    answers: ['9600 amperes', '200 amperes', '0.667 amperes', '1.5 amperes'],
    correctIndex: 3,
    explanation: 'I = E/R = 120 V / 80 ohms = 1.5 amperes.',
    category: 'T5',
    subcategory: 'T5D',
  },
  {
    id: 'T5D08',
    question: 'What is the current through a 100-ohm resistor connected across 200 volts?',
    answers: ['20,000 amperes', '0.5 amperes', '2 amperes', '1 ampere'],
    correctIndex: 2,
    explanation: 'I = E/R = 200 V / 100 ohms = 2 amperes.',
    category: 'T5',
    subcategory: 'T5D',
  },
  {
    id: 'T5D09',
    question: 'What is the current through a 24-ohm resistor connected across 240 volts?',
    answers: ['24,000 amperes', '0.1 amperes', '10 amperes', '216 amperes'],
    correctIndex: 2,
    explanation: 'I = E/R = 240 V / 24 ohms = 10 amperes.',
    category: 'T5',
    subcategory: 'T5D',
  },
  {
    id: 'T5D10',
    question: 'What is the voltage across a 2-ohm resistor if a current of 0.5 amperes flows through it?',
    answers: ['1 volt', '0.25 volts', '2.5 volts', '1.5 volts'],
    correctIndex: 0,
    explanation: 'E = I × R = 0.5 A × 2 ohms = 1 volt.',
    category: 'T5',
    subcategory: 'T5D',
  },
  {
    id: 'T5D11',
    question: 'What is the voltage across a 10-ohm resistor if a current of 1 ampere flows through it?',
    answers: ['1 volt', '10 volts', '11 volts', '9 volts'],
    correctIndex: 1,
    explanation: 'E = I × R = 1 A × 10 ohms = 10 volts.',
    category: 'T5',
    subcategory: 'T5D',
  },
  {
    id: 'T5D12',
    question: 'What is the voltage across a 10-ohm resistor if a current of 2 amperes flows through it?',
    answers: ['8 volts', '0.2 volts', '12 volts', '20 volts'],
    correctIndex: 3,
    explanation: 'E = I × R = 2 A × 10 ohms = 20 volts.',
    category: 'T5',
    subcategory: 'T5D',
  },
  {
    id: 'T5D13',
    question: 'What happens to current at the junction of two components in series?',
    answers: ['It divides equally between them', 'It is unchanged', 'It divides based on the value of the components', 'It is reduced by half'],
    correctIndex: 1,
    explanation: 'In a series circuit, the current is the same through all components. The current is unchanged at the junction of two series components.',
    category: 'T5',
    subcategory: 'T5D',
  },
  {
    id: 'T5D14',
    question: 'What happens to current at the junction of two components in parallel?',
    answers: ['It divides between them dependent on the value of the components', 'It is the same in both components', 'Its power multiplies', 'Its voltage divides'],
    correctIndex: 0,
    explanation: 'In a parallel circuit, current divides between the branches dependent on the value of the components.',
    category: 'T5',
    subcategory: 'T5D',
  },
  {
    id: 'T5D15',
    question: 'What is the voltage across each of two components in series with a voltage source?',
    answers: ['The same voltage as the source', 'Half the source voltage', 'It is determined by the type and internal resistance of the components', 'The sum of the voltages is equal to the applied voltage'],
    correctIndex: 3,
    explanation: 'In a series circuit, the sum of the voltage drops across each component equals the applied voltage (Kirchhoff\'s Voltage Law).',
    category: 'T5',
    subcategory: 'T5D',
  },
];
