import type { Question } from '@/types/question';

export const questionsPart4: Question[] = [
  // === T6A - Resistors, Capacitors & Inductors ===
  {
    id: 'T6A01',
    question: 'What electrical component opposes the flow of current in a DC circuit?',
    answers: ['Inductor', 'Resistor', 'Inverter', 'Transformer'],
    correctIndex: 1,
    explanation: 'A resistor opposes the flow of current in a DC circuit. It provides resistance to the flow of electrons.',
    category: 'T6',
    subcategory: 'T6A',
  },
  {
    id: 'T6A02',
    question: 'What type of component is often used as an adjustable volume control?',
    answers: ['Fixed resistor', 'Power resistor', 'Potentiometer', 'Transformer'],
    correctIndex: 2,
    explanation: 'A potentiometer is often used as an adjustable volume control. It is a variable resistor.',
    category: 'T6',
    subcategory: 'T6A',
  },
  {
    id: 'T6A03',
    question: 'What electrical parameter is controlled by a potentiometer?',
    answers: ['Inductance', 'Resistance', 'Capacitance', 'Field strength'],
    correctIndex: 1,
    explanation: 'A potentiometer controls resistance. It is a variable resistor that can be adjusted.',
    category: 'T6',
    subcategory: 'T6A',
  },
  {
    id: 'T6A04',
    question: 'What electrical component stores energy in an electric field?',
    answers: ['Resistor', 'Capacitor', 'Inductor', 'Diode'],
    correctIndex: 1,
    explanation: 'A capacitor stores energy in an electric field between its plates.',
    category: 'T6',
    subcategory: 'T6A',
  },
  {
    id: 'T6A05',
    question: 'What type of electrical component consists of two or more conductive surfaces separated by an insulator?',
    answers: ['Resistor', 'Potentiometer', 'Oscillator', 'Capacitor'],
    correctIndex: 3,
    explanation: 'A capacitor consists of two or more conductive surfaces (plates) separated by an insulator (dielectric).',
    category: 'T6',
    subcategory: 'T6A',
  },
  {
    id: 'T6A06',
    question: 'What type of electrical component stores energy in a magnetic field?',
    answers: ['Resistor', 'Capacitor', 'Inductor', 'Diode'],
    correctIndex: 2,
    explanation: 'An inductor stores energy in a magnetic field when current flows through it.',
    category: 'T6',
    subcategory: 'T6A',
  },
  {
    id: 'T6A07',
    question: 'What electrical component usually is constructed as a coil of wire?',
    answers: ['Switch', 'Capacitor', 'Diode', 'Inductor'],
    correctIndex: 3,
    explanation: 'An inductor is usually constructed as a coil of wire.',
    category: 'T6',
    subcategory: 'T6A',
  },
  {
    id: 'T6A08',
    question: 'What is the function of an SPDT switch?',
    answers: ['A single circuit is opened or closed', 'Two circuits are opened or closed', 'A single circuit is routed between two other circuits', 'Two circuits each open or close a single circuit'],
    correctIndex: 2,
    explanation: 'An SPDT (Single Pole, Double Throw) switch routes a single circuit between two other circuits.',
    category: 'T6',
    subcategory: 'T6A',
  },
  // === T6B - Semiconductors ===
  {
    id: 'T6B01',
    question: 'What class of electronic components uses a voltage or current signal to control current flow?',
    answers: ['Capacitors', 'Inductors', 'Resistors', 'Transistors'],
    correctIndex: 3,
    explanation: 'Transistors are active components that use a voltage or current signal to control current flow.',
    category: 'T6',
    subcategory: 'T6B',
  },
  {
    id: 'T6B02',
    question: 'What electronic component allows current to flow in only one direction?',
    answers: ['Resistor', 'Fuse', 'Diode', 'Driven element'],
    correctIndex: 2,
    explanation: 'A diode allows current to flow in only one direction.',
    category: 'T6',
    subcategory: 'T6B',
  },
  {
    id: 'T6B03',
    question: 'Which of these components can be used as an electronic switch?',
    answers: ['Resistor', 'Potentiometer', 'Transistor', 'Thermistor'],
    correctIndex: 2,
    explanation: 'A transistor can be used as an electronic switch, controlling current flow with a small input signal.',
    category: 'T6',
    subcategory: 'T6B',
  },
  {
    id: 'T6B04',
    question: 'Which of the following components can consist of three regions of semiconductor material?',
    answers: ['Alternator', 'Transistor', 'Triode', 'Pentagrid converter'],
    correctIndex: 1,
    explanation: 'A transistor consists of three regions of semiconductor material, forming either NPN or PNP configurations.',
    category: 'T6',
    subcategory: 'T6B',
  },
  {
    id: 'T6B05',
    question: 'What type of transistor has a gate, drain, and source?',
    answers: ['Bipolar junction transistor', 'Field-effect transistor', 'NPN transistor', 'P-N-P transistor'],
    correctIndex: 1,
    explanation: 'A Field-Effect Transistor (FET) has three terminals: gate, drain, and source.',
    category: 'T6',
    subcategory: 'T6B',
  },
  {
    id: 'T6B06',
    question: 'How is the cathode lead of a semiconductor diode often marked on the package?',
    answers: ['With the word \'cathode\'', 'With a stripe', 'With the letter C', 'With the letter K'],
    correctIndex: 1,
    explanation: 'The cathode lead of a semiconductor diode is often marked with a stripe on the package.',
    category: 'T6',
    subcategory: 'T6B',
  },
  {
    id: 'T6B07',
    question: 'What causes a light-emitting diode (LED) to emit light?',
    answers: ['Forward current through the LED causes electrons to fall into lower energy levels, releasing energy in the form of photons', 'High voltage causes the semiconductor to emit light', 'Harmonic generation causes light emission', 'Capacitance causes emission of light when the voltage changes'],
    correctIndex: 0,
    explanation: 'When forward current flows through an LED, electrons fall into lower energy levels and release energy in the form of photons (light).',
    category: 'T6',
    subcategory: 'T6B',
  },
  {
    id: 'T6B08',
    question: 'What does the abbreviation LED stand for?',
    answers: ['Low Emission Diode', 'Light Emitting Diode', 'Liquid Emission Detector', 'Long Echo Delay'],
    correctIndex: 1,
    explanation: 'LED stands for Light Emitting Diode.',
    category: 'T6',
    subcategory: 'T6B',
  },
  {
    id: 'T6B09',
    question: 'What does the abbreviation FET stand for?',
    answers: ['Field Effect Transistor', 'Fast Electron Transistor', 'Free Electron Transmitter', 'Frequency Emission Transmitter'],
    correctIndex: 0,
    explanation: 'FET stands for Field Effect Transistor.',
    category: 'T6',
    subcategory: 'T6B',
  },
  {
    id: 'T6B10',
    question: 'What are the three electrodes of a field effect transistor?',
    answers: ['Emitter, base, collector', 'Cathode, grid, plate', 'Source, gate, drain', 'Cathode, gate, anode'],
    correctIndex: 2,
    explanation: 'The three electrodes of a field effect transistor are source, gate, and drain.',
    category: 'T6',
    subcategory: 'T6B',
  },
  {
    id: 'T6B11',
    question: 'What is the term that describes a transistor\'s ability to amplify a signal?',
    answers: ['Gain', 'Forward resistance', 'Forward voltage drop', 'On resistance'],
    correctIndex: 0,
    explanation: 'Gain is the term that describes a transistor\'s ability to amplify a signal.',
    category: 'T6',
    subcategory: 'T6B',
  },
  // === T6C - Circuit Diagrams ===
  {
    id: 'T6C01',
    question: 'What is the name of an electrical wiring diagram that uses standard component symbols?',
    answers: ['Bill of materials', 'Connector pinout', 'Schematic', 'Flow chart'],
    correctIndex: 2,
    explanation: 'A schematic is an electrical wiring diagram that uses standard component symbols.',
    category: 'T6',
    subcategory: 'T6C',
  },
  {
    id: 'T6C02',
    question: 'What is component 1 in figure T-1?',
    answers: ['Resistor', 'Transistor', 'Battery', 'Connector'],
    correctIndex: 2,
    explanation: 'Component 1 in figure T-1 represents a battery or power source.',
    category: 'T6',
    subcategory: 'T6C',
  },
  {
    id: 'T6C03',
    question: 'What is component 2 in figure T-1?',
    answers: ['Resistor', 'Transistor', 'Indicator lamp', 'Connector'],
    correctIndex: 0,
    explanation: 'Component 2 in figure T-1 represents a resistor.',
    category: 'T6',
    subcategory: 'T6C',
  },
  {
    id: 'T6C04',
    question: 'What is component 3 in figure T-1?',
    answers: ['Resistor', 'Transistor', 'Lamp', 'Ground'],
    correctIndex: 0,
    explanation: 'Component 3 in figure T-1 represents a resistor.',
    category: 'T6',
    subcategory: 'T6C',
  },
  {
    id: 'T6C05',
    question: 'What is component 4 in figure T-1?',
    answers: ['Resistor', 'Transistor', 'Battery', 'Ground'],
    correctIndex: 3,
    explanation: 'Component 4 in figure T-1 represents a ground connection.',
    category: 'T6',
    subcategory: 'T6C',
  },
  {
    id: 'T6C06',
    question: 'What is component 6 in figure T-2?',
    answers: ['Resistor', 'Capacitor', 'Regulator IC', 'Transistor'],
    correctIndex: 1,
    explanation: 'Component 6 in figure T-2 represents a capacitor.',
    category: 'T6',
    subcategory: 'T6C',
  },
  {
    id: 'T6C07',
    question: 'What is component 8 in figure T-2?',
    answers: ['Resistor', 'Capacitor', 'Inductor', 'Regulator IC'],
    correctIndex: 2,
    explanation: 'Component 8 in figure T-2 represents an inductor.',
    category: 'T6',
    subcategory: 'T6C',
  },
  {
    id: 'T6C08',
    question: 'What is component 9 in figure T-2?',
    answers: ['Variable capacitor', 'Variable inductor', 'Variable resistor', 'Variable transformer'],
    correctIndex: 0,
    explanation: 'Component 9 in figure T-2 represents a variable capacitor.',
    category: 'T6',
    subcategory: 'T6C',
  },
  {
    id: 'T6C09',
    question: 'What is component 4 in figure T-2?',
    answers: ['Variable inductor', 'Double-pole switch', 'Potentiometer', 'Transformer'],
    correctIndex: 2,
    explanation: 'Component 4 in figure T-2 represents a potentiometer (variable resistor).',
    category: 'T6',
    subcategory: 'T6C',
  },
  {
    id: 'T6C10',
    question: 'What is component 3 in figure T-3?',
    answers: ['Connector', 'Meter', 'Variable capacitor', 'Variable inductor'],
    correctIndex: 1,
    explanation: 'Component 3 in figure T-3 represents a meter.',
    category: 'T6',
    subcategory: 'T6C',
  },
  {
    id: 'T6C11',
    question: 'What is component 4 in figure T-3?',
    answers: ['Ground', 'Solar cell', 'Zener diode', 'Light-emitting diode'],
    correctIndex: 3,
    explanation: 'Component 4 in figure T-3 represents a light-emitting diode (LED).',
    category: 'T6',
    subcategory: 'T6C',
  },
  // === T6D - Component Functions ===
  {
    id: 'T6D01',
    question: 'What two devices in an Amateur Radio station might be connected using a USB interface?',
    answers: ['Amplifier and antenna', 'Computer and transceiver', 'Power supply and amplifier', 'Microphone and transceiver'],
    correctIndex: 1,
    explanation: 'A computer and transceiver are often connected using a USB interface for digital mode operations.',
    category: 'T6',
    subcategory: 'T6D',
  },
  {
    id: 'T6D02',
    question: 'What is a function of a digital mode hot spot?',
    answers: ['It provides a grounding point for digital circuits', 'It is an interface between a radio and a computer for digital modes', 'It is an interface between a radio and a computer for voice modes', 'It is an interface between a radio and a computer for CW'],
    correctIndex: 1,
    explanation: 'A digital mode hot spot is an interface between a radio and a computer for digital modes.',
    category: 'T6',
    subcategory: 'T6D',
  },
  {
    id: 'T6D03',
    question: 'Which of the following devices or circuits changes an alternating current into a varying direct current signal?',
    answers: ['Transformer', 'Rectifier', 'Amplifier', 'Reflector'],
    correctIndex: 1,
    explanation: 'A rectifier changes alternating current (AC) into direct current (DC).',
    category: 'T6',
    subcategory: 'T6D',
  },
  {
    id: 'T6D04',
    question: 'What is the main function of the ferrite core in an inductor?',
    answers: ['To increase the current carrying capacity', 'To increase the inductance', 'To reduce the inductance', 'To reduce the current carrying capacity'],
    correctIndex: 1,
    explanation: 'The ferrite core in an inductor increases the inductance compared to an air-core inductor of the same size.',
    category: 'T6',
    subcategory: 'T6D',
  },
  {
    id: 'T6D05',
    question: 'What is the function of a product detector?',
    answers: ['It amplifies the signal', 'It converts the signal to a lower frequency', 'It detects CW and SSB signals', 'It generates the carrier signal'],
    correctIndex: 2,
    explanation: 'A product detector is used to demodulate CW and SSB signals by mixing the received signal with a locally generated carrier.',
    category: 'T6',
    subcategory: 'T6D',
  },
  {
    id: 'T6D06',
    question: 'What is a triband antenna?',
    answers: ['An antenna with three driven elements', 'An antenna that operates on three bands', 'An antenna with three reflectors', 'An antenna with three directors'],
    correctIndex: 1,
    explanation: 'A triband antenna is an antenna that operates on three different frequency bands.',
    category: 'T6',
    subcategory: 'T6D',
  },
  {
    id: 'T6D07',
    question: 'Which of the following is a common reason to use a shielded wire?',
    answers: ['To decrease the resistance of the wire', 'To increase the current carrying capability of the wire', 'To prevent coupling of unwanted signals to and from the wire', 'To couple the wire to other signals'],
    correctIndex: 2,
    explanation: 'Shielded wire is used to prevent coupling of unwanted signals to and from the wire, reducing interference.',
    category: 'T6',
    subcategory: 'T6D',
  },
  {
    id: 'T6D08',
    question: 'Which of the following displays an electrical quantity as a numeric value?',
    answers: ['Potentiometer', 'Transistor', 'Meter', 'Relay'],
    correctIndex: 2,
    explanation: 'A meter displays an electrical quantity (such as voltage, current, or power) as a numeric value.',
    category: 'T6',
    subcategory: 'T6D',
  },
  {
    id: 'T6D09',
    question: 'What type of circuit controls the amount of voltage from a power supply?',
    answers: ['Regulator', 'Oscillator', 'Filter', 'Phase inverter'],
    correctIndex: 0,
    explanation: 'A regulator circuit controls the amount of voltage from a power supply, maintaining a constant output voltage.',
    category: 'T6',
    subcategory: 'T6D',
  },
  {
    id: 'T6D10',
    question: 'What component is commonly used to change 120V AC house current to a lower AC voltage for other uses?',
    answers: ['Variable capacitor', 'Transformer', 'Transistor', 'Diode'],
    correctIndex: 1,
    explanation: 'A transformer is commonly used to change 120V AC house current to a lower AC voltage.',
    category: 'T6',
    subcategory: 'T6D',
  },
  {
    id: 'T6D11',
    question: 'Which of the following is commonly used as a visual indicator?',
    answers: ['LED', 'FET', 'Zener diode', 'Bipolar transistor'],
    correctIndex: 0,
    explanation: 'An LED (Light Emitting Diode) is commonly used as a visual indicator.',
    category: 'T6',
    subcategory: 'T6D',
  },
  {
    id: 'T6D12',
    question: 'Which of the following is combined with an inductor to make a filter?',
    answers: ['Resistor', 'Zener diode', 'Potentiometer', 'Capacitor'],
    correctIndex: 3,
    explanation: 'A capacitor is combined with an inductor to make a filter, such as an LC filter.',
    category: 'T6',
    subcategory: 'T6D',
  },
  {
    id: 'T6D13',
    question: 'What is the name of a circuit that generates a signal at a specific frequency?',
    answers: ['Reactance modulator', 'Product detector', 'Low-pass filter', 'Oscillator'],
    correctIndex: 3,
    explanation: 'An oscillator is a circuit that generates a signal at a specific frequency.',
    category: 'T6',
    subcategory: 'T6D',
  },
  {
    id: 'T6D14',
    question: 'What is the function of a mixer in a superheterodyne receiver?',
    answers: ['To reject unwanted signals', 'To shift the received signal to a lower frequency', 'To increase the gain of the received signal', 'To filter the received signal'],
    correctIndex: 1,
    explanation: 'A mixer in a superheterodyne receiver shifts the received signal to a lower (intermediate) frequency for easier processing.',
    category: 'T6',
    subcategory: 'T6D',
  },
];
